Python 3.11.0a5 (main, Feb  3 2022, 19:32:53) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.




====== RESTART: E:/pythonpractice48/123.py ======

====== RESTART: E:/pythonpractice48/123.py ======
cats	care
	source
	of	internret	memes
print('\\'*4)
\\\\
print('\\\n'*3)
\
\
\

print('good-boy')
good-boy

====== RESTART: E:/pythonpractice48/123.py ======
cats	care
	source
	of	internret	memes
\\\\
\
\
\


====== RESTART: E:/pythonpractice48/123.py ======
cats	care
	source
	of	internret	memes
\\\\
\
\
\

good-boy

====== RESTART: E:/pythonpractice48/123.py ======
'abc' 'def'
'abc'+'def'
'abc' + 'def'

SyntaxError: multiple statements found while compiling a single statement
 ======
'abc' 'def'
SyntaxError: unexpected indent
 ======
'abc' 'def
SyntaxError: unexpected indent
'ah' 'fg'
'ahfg'
's' + 's'
'ss'
x='seh'
y='ned'
x+y
'sehned'
x y
SyntaxError: invalid syntax
s1='sss'*4
s2
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    s2
NameError: name 's2' is not defined. Did you mean: 's1'?
s1='sss'*4
s1
'ssssssssssss'
s2='asd'*4
print(s2)
asdasdasdasd
s2='asd '*4
print(s2)
asd asd asd asd 
s2
'asd asd asd asd '

====== RESTART: E:/pythonpractice48/123.py ======
6
6
print(len(s))
8
 'abc' +str(5)
 
SyntaxError: unexpected indent
'abc' +str(5)
'abc5'
'abc' * str(5)
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    'abc' * str(5)
TypeError: can't multiply sequence by non-int of type 'str'
'abc' *str(5)
Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    'abc' *str(5)
TypeError: can't multiply sequence by non-int of type 'str'
'fhf' +5
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    'fhf' +5
TypeError: can only concatenate str (not "int") to str
'fhf' + 5
Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    'fhf' + 5
TypeError: can only concatenate str (not "int") to str
'sdg' +float(95.0)
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    'sdg' +float(95.0)
TypeError: can only concatenate str (not "float") to str
str(3.0) * 3
'3.03.03.0'
str(123.0) * 3
'123.0123.0123.0'

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer==> 12
x is: 2424

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer==> 4
x is: 88

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 5
5 , 0 0

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 4
4 , 0 0

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 64
64 , 6 6

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 10
10 , 1 1

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 64
64 , 6 6

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 64
64@,@6@6

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 64
64,66

====== RESTART: E:/pythonpractice48/123.py ======
enter an integer ==> 64
64 , 6 6

s1='"hi mom",i said."how are you"'
s1
'"hi mom",i said."how are you"'
s2='"hi mom",i said.'"how are you"
s2
'"hi mom",i said.how are you'
s1="""'hi mom",i said.'"how are you"'"""
s1
'\'hi mom",i said.\'"how are you"\''
s3="""'hi mom",i said.'"how are you"'"""
s3
'\'hi mom",i said.\'"how are you"\''
s5=""i want samosa!"'
SyntaxError: unterminated string literal (detected at line 1)
s6="\"i want chamocha\"\n\t'yes''\n\t\"a have samosa\""
s6
'"i want chamocha"\n\t\'yes\'\'\n\t"a have samosa"'

636363
636363
123456789*123
15185185047
2/5
0.4
'apple';b='paple'
'apple'
a
Traceback (most recent call last):
  File "<pyshell#51>", line 1, in <module>
    a
NameError: name 'a' is not defined
a='apple';b='paple'
a
'apple'
b
'paple'
sorted(a)
['a', 'e', 'l', 'p', 'p']
sorted(b)
['a', 'e', 'l', 'p', 'p']
'apple'.split()
['apple']
'apple paple'.split(',')
['apple paple']
'a,p,p,l,e'.split(',')
['a', 'p', 'p', 'l', 'e']
'app.le.is.sweet'.split(' ')
['app.le.is.sweet']
'today is monday'.split(' ')
['today', 'is', 'monday']
'today is monday'.split()
['today', 'is', 'monday']
'computer'.split(',')
['computer']
'computer'.split(' ')
['computer']
'computer'.split()
['computer']
'apple mango'.split()
['apple', 'mango']

= RESTART: E:/pythonpractice48/day5/program02.py
0
Traceback (most recent call last):
  File "E:/pythonpractice48/day5/program02.py", line 8, in <module>
    print(checkanagram(inp[10],inp[1]))
IndexError: list index out of range
mca cam
SyntaxError: invalid syntax

= RESTART: E:/pythonpractice48/day5/program02.py
mca cam
Traceback (most recent call last):
  File "E:/pythonpractice48/day5/program02.py", line 8, in <module>
    print(checkanagram(inp[10],inp[1]))
IndexError: list index out of range

= RESTART: E:/pythonpractice48/day5/program02.py
mca cam
yes

 = RESTART: E:/pythonpractice48/day5/program02.py
cam dam
no
inp
['cam', 'dam']

= RESTART: E:/pythonpractice48/day5/program02.py
rev dev
no

= RESTART: E:/pythonpractice48/day5/program02.py
rev ver
yes

= RESTART: E:/pythonpractice48/day5/program02.py
rev rve
yes

= RESTART: E:/pythonpractice48/day5/program02.py
ddve dve
no

= RESTART: E:/pythonpractice48/day5/program02.py
ddve edvd
yes

= RESTART: E:/pythonpractice48/day5/program03.py
medam
Traceback (most recent call last):
  File "E:/pythonpractice48/day5/program03.py", line 8, in <module>
    print(checkpalindrome(inp[0],inp[1]))
IndexError: list index out of range

= RESTART: E:/pythonpractice48/day5/program03.py
madam
yes

= RESTART: E:/pythonpractice48/day5/program03.py
121
yes

= RESTART: E:/pythonpractice48/day5/program03.py
123
yes

= RESTART: E:/pythonpractice48/day5/program03.py
123
no

= RESTART: E:/pythonpractice48/day5/extract_vowels.py
to day is a holiday due to ysuri bday
Traceback (most recent call last):
  File "E:/pythonpractice48/day5/extract_vowels.py", line 9, in <module>
    a=extract_vowel(str1)
  File "E:/pythonpractice48/day5/extract_vowels.py", line 3, in extract_vowel
    for i in s:
NameError: name 's' is not defined. Did you mean: 's0'?

= RESTART: E:/pythonpractice48/day5/extract_vowels.py
today is holidat due to ysuri bday
vowel: 

= RESTART: E:/pythonpractice48/day5/extract_vowels.py
revanth
vowel: 

= RESTART: E:/pythonpractice48/day5/extract_vowels.py
revanth


= RESTART: E:/pythonpractice48/day5/extract_vowels.py
enter the string:revanth
revanth
vowel: 

= RESTART: E:/pythonpractice48/day5/extract_vowels.py
revanth
i= r
vowel: 

= RESTART: E:/pythonpractice48/day5/extract_vowels.py
revanth
vowel: ea

= RESTART: E:/pythonpractice48/day5/extract_conso.py
\
vowel: \




= RESTART: E:/pythonpractice48/day5/extract_conso.py
revanth
vowel: rvnth
